# Generated by Django 2.1.1 on 2018-10-11 18:47

import cloudfiles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('img', 'Image'), ('video', 'Video'), ('music', 'Music'), ('doc', 'Document'), ('file', 'File')], default='file', max_length=50)),
                ('thumbnail', models.ImageField(null=True, upload_to=cloudfiles.models.filesImagePath)),
                ('name', models.CharField(blank=True, default='Default File', max_length=100)),
                ('size', models.CharField(blank=True, default='0', max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('encoding', models.CharField(blank=True, default='...', max_length=100)),
                ('path', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Default Folder', max_length=100)),
                ('path', models.CharField(blank=True, default='main', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudfiles.Folder'),
        ),
    ]
