# Generated by Django 2.1.1 on 2018-10-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudfiles', '0002_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.CharField(blank=True, default='main', max_length=100),
        ),
    ]
