# Generated by Django 2.1a1 on 2018-07-17 20:18

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180711_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default='general'),
        ),
    ]
