# Generated by Django 2.1.1 on 2018-09-29 11:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import skills.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Field', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Skill', max_length=200)),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(null=True, upload_to=skills.models.get_image_path)),
                ('order', models.IntegerField(blank=True, default=1)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Field')),
            ],
        ),
    ]
