# Generated by Django 2.1.1 on 2018-10-01 21:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20180929_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
