# Generated by Django 2.1a1 on 2018-07-30 18:50

import aboutme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=250)),
                ('bio', models.TextField()),
                ('tags', models.TextField(default="''")),
                ('work', models.CharField(max_length=500)),
                ('education', models.CharField(max_length=500)),
                ('profileimage', models.ImageField(blank=True, null=True, upload_to=aboutme.models.get_image_path)),
            ],
        ),
    ]
