# Generated by Django 2.1a1 on 2018-08-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='email_url',
            field=models.CharField(default='@', max_length=500),
        ),
        migrations.AddField(
            model_name='me',
            name='github_url',
            field=models.CharField(default='https://github.com', max_length=500),
        ),
        migrations.AddField(
            model_name='me',
            name='linkedin_url',
            field=models.CharField(default='https://www.linkedin.com', max_length=500),
        ),
        migrations.AddField(
            model_name='me',
            name='twitter_url',
            field=models.CharField(default='https://twitter.com', max_length=500),
        ),
    ]
