# Generated by Django 2.1a1 on 2018-08-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20180801_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='me',
            name='email_url',
        ),
        migrations.AddField(
            model_name='me',
            name='email',
            field=models.CharField(default='profile', max_length=500),
        ),
    ]
