# Generated by Django 2.1a1 on 2018-08-06 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, default='Oxford University', max_length=200)),
                ('certification', models.CharField(default='Software Engineer', max_length=200)),
                ('academic_discipline', models.CharField(default='Software Engineer', max_length=200)),
                ('mark', models.DecimalField(decimal_places=2, default=5.55, max_digits=3, null=True)),
                ('description', models.TextField(default='My education description', max_length=200)),
                ('startdate', models.DateField(blank=True, default=datetime.date.today)),
                ('finaldate', models.DateField(auto_now_add=True, null=True)),
                ('activities', models.TextField(default='Football Team & Choir', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='Software Developer', max_length=200)),
                ('company', models.CharField(blank=True, default='Google', max_length=200)),
                ('location', models.CharField(default='Madrid, Spain', max_length=200)),
                ('startdate', models.DateField(blank=True, default=datetime.date.today)),
                ('finaldate', models.DateField(auto_now_add=True, null=True)),
                ('description', models.TextField(default='My Job description')),
            ],
        ),
    ]
