# Generated by Django 2.1a1 on 2018-08-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mycv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='cv_education',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cv.Mycv'),
        ),
        migrations.AddField(
            model_name='experience',
            name='cv_experience',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cv.Mycv'),
        ),
    ]
