# Generated by Django 2.1a1 on 2018-08-07 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20180807_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cv_education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cv.Mycv'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='cv_experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cv.Mycv'),
        ),
    ]
