# Generated by Django 2.1a1 on 2018-08-17 18:45

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_experience_experience_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_image',
            field=models.ImageField(null=True, upload_to=cv.models.get_image_path),
        ),
    ]
