# Generated by Django 2.1a1 on 2018-08-17 18:53

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20180817_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='experience_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(null=True, upload_to=cv.models.get_image_path),
        ),
    ]
