# Generated by Django 2.1a1 on 2018-08-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_education_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycv',
            name='display',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
