# Generated by Django 2.1a1 on 2018-08-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_mycv_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycv',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
